version: '3'

services:
  app:
    build:
      context: ./App
    volumes:
      - ./App:/App
    # Not Exposing Any Port Since Both `app` & `nginx` are on the same network `my_network_v1`
    # ports:
    #   - "5011"
    command: gunicorn --bind 0.0.0.0:5011 app:app

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"

networks:
  default:
    external:
      name: my_network_v1
