version: '3'

services:
  app:
    container_name: app
    build: 
      context: ./App
    ports:
      - "8000:8000"
    volumes:
      - ./App:/App
    command: gunicorn --bind 0.0.0.0:8000 app:app
